// ERRORS ACTIONS
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//AUTH ACTIONS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';


//PAGE ACTIONS
export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADED = 'PAGE_LOADED';

//DASHBOARD ACTIONS
export const SET_DASHBOARD = 'SET_DASHBOARD';


// VENDORS ACTION
export const SET_VENDORS = 'SET_VENDORS';
export const SET_SINGLE_VENDOR = 'SET_SINGLE_VENDOR';
export const SET_SINGLE_VENDORS_PROPERTIES = 'SET_SINGLE_VENDORS_PROPERTIES';
export const UPDATE_VENDOR_STATUS = 'UPDATE_VENDOR_STATUS';


//USERS ACTION
export const SET_USERS = 'SET_USERS';
export const SET_SINGLE_USER = 'SET_SINGLE_USER';
export const SET_USER_STATE = 'SET_USER_STATE';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';

export const GET_SINGLE_PROPERTY = 'GET_SINGLE_PROPERTY';
export const GET_ALL_PROPERTIES = 'GET_ALL_PROPERTIES';

//ACCOUNTS ACTIONS
export const GET_UPDATE_ACCOUNT_DATA = 'GET_UPDATE_ACCOUNT_DATA';
export const GET_PROPERTY_FEES_DATA = 'GET_PROPERTY_FEES_DATA';
